### ISSUE TITLE
Problems on the "What is TaxBrain?" page

### ISSUE THREAD

**Issue by martinholmer** [ospc-org/ospc.org#815]
When users scroll to the bottom of the "What is TaxBrain?" page they see this:

![screen shot 2018-01-29 at 10 35 34 am](https://user-images.githubusercontent.com/12170745/35518691-3a6ed72e-04e0-11e8-94ff-5ec85bf3b519.png)

There are two problem here:

1. The asterisk does not "point" anywhere.  (Should there be an `*` character in front of the "These members have ..." section?)

2. Clicking on the " T.J. Alumbaugh, Continuum Analytics" link produces this page: [RESOLVED BY #818]

![screen shot 2018-01-29 at 10 25 37 am](https://user-images.githubusercontent.com/12170745/35518895-d29ac8f0-04e0-11e8-877b-2d6f6c59a692.png)

**Comment by hdoupe** [comment]
@martinholmer Thanks for pointing this out.

@codekansas can you swap out T.J.'s link with a link to his github profile?
https://github.com/talumbau

@MattHJensen what is the asterisk supposed to refer to?

**Comment by martinholmer** [comment]
Pull request #818 resolved the [second problem](https://github.com/ospc-org/ospc.org/issues/815#issue-292453914) reported in this issue, but not the first.  Are there any plans to either drop the `*` (which seems like the better option to me) or add a `*` at the start of the "These members ..." phrase?

**Comment by MattHJensen** [comment]
I'm happy with dropping the `*`. (sorry I missed the question to me in January).

**Comment by martinholmer** [comment]
Pull request #944 resolves issue #815
