### ISSUE TITLE
Regressions in TaxBrain GUI interface

### ISSUE THREAD

**Issue by martinholmer** [ospc-org/ospc.org#883]
With the new 1.5.0 version of PolicyBrain, the TaxBrain GUI input page has suffered two significant regressions.

1. Users cannot scroll down the left-hand pane to get quickly to sections or the "Show Me the Results" button. [UNRESOLVED AS OF 2018-Nov-06]

2. Users cannot simulate current-law policy because TaxBrain now forces users to enter a reform. [RESOLVED BY #905]

**Comment by martinholmer** [comment]
Pull request #905 resolved the [second problem](https://github.com/ospc-org/ospc.org/issues/883#issue-310907728) originally reported in this issue, but the first problem remains unresolved.

**Comment by hdoupe** [comment]
Thanks for re-upping the second problem @martinholmer.

**Comment by martinholmer** [comment]
Presumably TaxBrain issue #883 will be fixed when switching to the new webapp infrastructure.
