### ISSUE TITLE
About TaxBrain dynamic simulation behavioral elasticities

### ISSUE THREAD

**Issue by martinholmer** [ospc-org/ospc.org#933]
This is not a TaxBrain enhancement request or bug report; it is just a simple question about how it works.

When I get to the static results page, click on "Link to Dynamic Simulations", and click on "Partial Equilibrium Simulation", I am presented with boxes for three elasticities.  Am I to assume that I should specify a single number in a box (if I want that elasticity to be non-zero)?  There is no start year and entering`*,*,*,-0.25` in a box doesn't seem to work.  So, am I correct in assuming that TaxBrain applies each non-zero elasticity to every one of the budget years?  I'm fine with that, but I just want to make sure I understand how TaxBrain works.

@hdoupe

**Comment by martinholmer** [comment]
After further work with TaxBrain, I now see that the three behavioral-response elasticities can be specified to vary by calendar year.  I've answered my own question, so I'm closing issue #933.

**Comment by hdoupe** [comment]
@martinholmer Sorry for the delayed response. It seems like you have this figured out. If you're interested in my current thinking on how the behavioral parameters (and other parameters that can be applied in addition to the static parameters) you can check out the test site: https://ospc-test.herokuapp.com/taxbrain/

I think having a single page for each `taxcalc` API endpoint (e.g. `run_nth_year_taxcalc`) would simplify the technology and give a better user experience.
