### ISSUE TITLE
Zeroes reported on Static Results page

### ISSUE THREAD

**Issue by siervicul** [ospc-org/ospc.org#947]
Beginning sometime yesterday, I've started getting results pages with mostly zeroes in the analysis tables.  The "total liabilities by calendar year (change)" table has nothing but zeroes except in the two right-most columns.  The difference by expanded income bin table has all zeroes in the "all tax units," "tax units with tax cut," "tax units with tax increase," and "total tax difference" columns.

**Comment by hdoupe** [comment]
@siervicul ospc.org was updated yesterday to use a new version of Tax-Calculator. I suspect that is why the results are different. Can you post a link to the outputs page that you are referring to?

**Comment by siervicul** [comment]
@hdoupe here's one, though I have the same result with every reform I try, and regardless of whether I use the PUF or CPS data source--all zeroes in the first table: https://www.ospc.org/taxbrain/37335/

I'm getting the same issue with Internet Explorer on a PC and Chrome on an iOS device.

**Comment by hdoupe** [comment]
Thanks @siervicul. I can confirm that this is an issue on the ospc.org side and not with Tax-Calculator. Something is happening after the data from Tax-Calculator is processed and when the data is rendered into the table. I'm trying to resolve this now.

**Comment by hdoupe** [comment]
@siervicul The bug fix for this is live at www.ospc.org. Can you confirm whether the issue has been resolved? Sorry for the delay in getting this up.

I think the explanation for this is that Tax-Calculator has started scaling its own results. Previously, TaxBrain scaled the results down to Billions, Millions, etc.
