### ISSUE TITLE
TaxBrain distribution/difference table problems

### ISSUE THREAD

**Issue by martinholmer** [ospc-org/ospc.org#954]
In PolicyBrain 1.7.6, there are still "Thousands" labels that should be "Millions".  That is clearly wrong.
Not clearly wrong, but questionable is rounding the number of filing units to the nearest whole million instead of to the nearest one-tenth of a million or to the nearest one-hundredth of a million.

<img width="1621" alt="screen shot 2019-01-14 at 3 13 53 pm" src="https://user-images.githubusercontent.com/12170745/51138917-6edc8580-1810-11e9-8f27-1003fe487168.png">

The bug in the decile tables (all zeros on the `0-10n` and the `0-10z` rows) is caused by a Tax-Calculator bug that was fixed in [Tax-Calculator pull request 2192](https://github.com/PSLmodels/Tax-Calculator/pull/2192).

**Comment by hdoupe** [comment]
@martinholmer which columns should have which units? I'll swap them out once I have this info.

**Comment by hdoupe** [comment]
@martinholmer said: 
> The bug in the decile tables (all zeros on the 0-10n and the 0-10z rows) is caused by a Tax-Calculator bug that was fixed in Tax-Calculator pull request 2192.

Hmm, this may be harder to fix. Will this patch be released before the release that drops the `Behavior` class?

**Comment by martinholmer** [comment]
@hdoupe asked:
> Will this patch [T-C PR #2192] be released before the release that drops the Behavior class?

No.  See pending release 0.25.0 [here](https://github.com/PSLmodels/Tax-Calculator/pull/2187/files#diff-5cafcf46bfb947f8e58fa5c16d39018c).

**Comment by hdoupe** [comment]
@martinholmer what do you think about applying the 2192 patch to the 0.24 release and doing a 0.24.1 release in addition to the 0.25.0 release? @andersonfrailey and I have been working on a new package that will integrate Tax-Calculator and Behavior-Responses. However, it's not ready for production yet, and I think that the TaxBrain users would value this bug-fix before the new tax integrator package is ready to go.

**Comment by martinholmer** [comment]
@hdoupe said in issue #954:
> I think that the TaxBrain users would value this bug-fix before the new tax integrator package is ready to go.

I don't see how the "value" could be much more than zero given that no TaxBrain users noticed this problem over the past **nine** months.  As noted [here](https://github.com/PSLmodels/Tax-Calculator/pull/2192#issue-244307378) the bug has been present since April 19, 2018, when Tax-Calculator 0.19.0 was released.

**Comment by hdoupe** [comment]
Ok I see. Thanks for the bug report @martinholmer.
